# Generated by Django 4.0.5 on 2022-06-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='ABC', max_length=100)),
                ('last_name', models.CharField(default='Xyz', max_length=100)),
                ('email', models.EmailField(default='haz@gmail.com', max_length=100)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
